version: '3.8'

services:
  # 1. DATABASE (PostgreSQL)
  # Stores both Keycloak data and our Movie App data
  postgres:
    image: postgres:15
    container_name: movie_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movie-net
    ports:
      - "5432:5432"

  # 2. IDENTITY PROVIDER (Keycloak)
  # Handles Login/Registration/Tokens
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: movie_keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - movie-net

  # 3. MESSAGE BROKER (RabbitMQ) - For Event Driven Architecture later
  rabbitmq:
    image: rabbitmq:3-management
    container_name: movie_rabbitmq
    ports:
      - "5672:5672"   # Messaging port
      - "15672:15672" # Management UI port
    networks:
      - movie-net

volumes:
  postgres_data:
    driver: local

networks:
  movie-net:
    driver: bridge